micronaut:
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
          - http://localhost:3000
          allowed-methods:
          - GET
          - POST
          - PUT
          - OPTIONS
          allowed-headers:
          - Authorization
          - Content-Type
  security:
    intercept-url-map:
    - pattern: /**
      http-method: OPTIONS
      access:
      - isAnonymous()
